# Generated by Django 3.2 on 2023-08-05 02:12

from django.db import migrations
from django.contrib.auth.models import User

def init_data(apps, schema_editor):
    obj=User.objects.create_user(
        username="admin",is_staff=True, is_active=True, is_superuser=True,password="123456"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data)
    ]
