# Generated by Django 3.2 on 2023-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20230805_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
