# Generated by Django 3.2 on 2023-08-05 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='registered_list',
            field=models.ManyToManyField(null=True, related_name='allregistered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='create_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
